version: "3.1"

services:
  web:
    container_name: search_app
    build: ./etc/apache2
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./etc/apache2/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${HTTP_PORT}:80
