version: "3.1"

services:
  db_mysql:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_mysql_data:/var/lib/mysql
      - ./etc/mysql/:/etc/mysql/conf.d:ro
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: "--max_allowed_packet=1000M --connect_timeout=72"
  web:
    container_name: property_web
    build: ./etc/apache2
    restart: always
    depends_on:
      - db_mysql
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./etc/apache2/hosts_dev.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./etc/apache2/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${HTTP_PORT}:80
    networks:
      techtest:
volumes:
  db_mysql_data:

networks:
  techtest:
